apiVersion: v1
kind: Service
metadata:
  name: game-2048-service
  namespace: 2048-game
spec:
  type: LoadBalancer
  selector:
    app: game-2048
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
